
mybatis:
  type-aliases-package: com.mei.pojo
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    username: root
    password: root
    #url: jdbc:mysql://8.129.39.157:3306/mall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true


    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  thymeleaf:
    cache: false

  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: utf-8
    cache: false

  redis:
    host: 8.129.39.157
    port: 6379
    database: 0
    password: mei123A
    timeout: 5000

  mail:
    username: 244258267@qq.com
    password: slxedtuhugkycagc
    host: smtp.qq.com

    properties:
      mail:
        smtp:
          ssl:
            enable: true